# Generated by Django 5.2.4 on 2025-08-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_tareas_alter_alumnos_options_alter_alumnos_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=12, verbose_name='Identificacion')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
                'ordering': ['-created'],
            },
        ),
    ]
