# Generated by Django 5.2.4 on 2025-08-17 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_maestros'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.tareas', verbose_name='Tarea'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
