# Generated by Django 5.2.4 on 2025-08-17 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alumnos_foto_alumnos_tarea_alter_alumnos_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('terminada', 'Terminada')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('fecha_asignada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Asignada')),
                ('fecha_terminada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Terminada')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.alumnos', verbose_name='Alumno')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.tareas', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
                'ordering': ['-fecha_asignada'],
                'unique_together': {('alumno', 'tarea')},
            },
        ),
    ]
