# Generated by Django 5.2.4 on 2025-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alumnotarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnotarea',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia'),
        ),
    ]
