# Generated by Django 5.2.4 on 2025-08-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_duda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Estrella de asistencia', max_length=100)),
                ('motivo', models.TextField()),
                ('imagen', models.ImageField(upload_to='reconocimientos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='registros.alumnos')),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.maestros')),
            ],
        ),
    ]
