# Generated by Django 5.2.4 on 2025-08-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='tarea',
        ),
        migrations.DeleteModel(
            name='Evidencia',
        ),
    ]
